//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointActivities.DB
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class BD_AIS_POLEntities : DbContext
    {
        public BD_AIS_POLEntities()
            : base("name=BD_AIS_POLEntities")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OS_INFO> OS_INFO { get; set; }
    }
}
